#!/usr/bin/env bash

catkin build phaser_ros --mem-limit 75% && catkin run_tests phaser_common && catkin run_tests phaser_core --no-deps && catkin_test_results ../../build/phaser_core && catkin_test_results ../../build/phaser_common
