#!/usr/bin/env zsh
REST=$@

rosrun phaser_core phaser_core_driver \
  --v=3 \
  --alsologtostderr=1 \
  --phaser_pre_enable_geometric_cloud_segmentation=true \
  --target_cloud=/home/berlukas/Documents/workspace/phaser_ws/src/phaser/phaser_test_data/test_clouds/arche/penguin/cloud0061.ply \
  --source_cloud=/home/berlukas/Documents/workspace/phaser_ws/src/phaser/phaser_test_data/test_clouds/arche/penguin/cloud0062.ply \
  --reg_cloud=./cloud01.ply \
  $REST
