#!/usr/bin/env bash

catkin build phaser_ros && catkin run_tests phaser_common && catkin run_tests phaser_core --no-deps && catkin run_tests phaser_pre && catkin_test_results ../../build/phaser_core && catkin_test_results ../../build/phaser_common && catkin_test_results ../../build/phaser_pre
