#!/usr/bin/env bash
REST=$@

rosrun phaser_ros phaser_ros \
    --alsologtostderr=1 \
    --v=3 \
		--enable_debug=true \
		--registration_algorithm=sph-mock-rotated \
		--datasource="ply" \
		--PlyReadDirectory="/home/berlukas/Documents/workspace/phaser_ws/src/packlo/phaser_test_data/test_clouds/kitti/1/" \
		--spherical_bandwith=64 \
		--mock_rotate_alpha_rad=3.1415 \
		--mock_rotate_beta_rad=0.4 \
		--mock_rotate_gamma_rad=1.7 \
    --z_score_filter_threshold=0.4 \
    --z_score_lag_max=15 \
    --z_score_threshold=3.0 \
    $REST
