#!/usr/bin/env zsh
REST=$@

rosrun phaser_ros phaser_ros \
    --alsologtostderr=1 \
    --v=3 \
		--enable_debug=true \
		--registration_algorithm="sph" \
		--datasource="ply" \
		--PlyReadDirectory="/home/berlukas/Documents/workspace/phaser_ws/src/packlo/phaser_test_data/test_clouds/kitti/1/" \
		--spherical_bandwith=71 \
		--phase_n_voxels=51 \
		--phase_discretize_lower=-30 \
		--phase_discretize_upper=30 \
    --z_score_filter_threshold=0.4 \
    --z_score_lag_max=15 \
    --z_score_threshold=3.0 \
    $REST
