#!/usr/bin/env bash
REST=$@

rosrun packlo packlo \
    --alsologtostderr=1 \
    --v=3 \
		--enable_debug=true \
		--registration_algorithm=sph-mock-translated \
		--spherical_bandwith=128 \
    --sampling_neighbors=4 \
		--mock_translate_x=4.0 \
		--mock_translate_y=0.0 \
		--mock_translate_z=0.0 \
    --phase_discretize_lower=-100 \
    --phase_discretize_upper=100 \
    --phase_n_voxels=101 \
    $REST
