#!/usr/bin/env bash
REST=$@

rosrun packlo packlo \
    --alsologtostderr=1 \
    --v=3 \
		--enable_debug=true \
		--registration_algorithm=sph-mock-translated \
		--spherical_bandwith=128 \
    --sampling_neighbors=4 \
		--mock_translate_x=42.0 \
		--mock_translate_y=48.0 \
		--mock_translate_z=35.0 \
    --phase_discretize_lower=-80 \
    --phase_discretize_upper=80 \
    --phase_n_voxels=201 \
    --z_score_lag=210 \
    --z_score_threshold=5.1 \
    --z_score_influence=0.05 \
    --z_score_filter_threshold=0.15 \
    $REST
