#!/usr/bin/env zsh
REST=$@

rosrun packlo packlo \
    --alsologtostderr=1 \
    --v=3 \
		--enable_debug=true \
		--registration_algorithm="sph" \
		--datasource="ply" \
		--PlyReadDirectory="/home/berlukas/Documents/workspace/maplab/src/packlo/test/test-data/gonzen/easy-submaps/" \
		--spherical_bandwith=120 \
		--phase_n_voxels=280 \
		--phase_discretize_lower=-70 \
		--phase_discretize_upper=70 \
    $REST
