#!/usr/bin/env bash
REST=$@

rosrun packlo packlo \
    --alsologtostderr=1 \
    --v=3 \
		--enable_debug=true \
		--app_mode="store_ply" \
		--PlyWriteDirectory="/home/berlukas/Documents/ply/" \
    $REST
